name = "Light Helper"
id = "LightHepler"
maintainer = "ACGGit Community,Atticus,小萌新"
version = "0.3.2"
tagline = "Light Helper"
blender_version_min = "4.2.0"
type = "add-on"
schema_version = "1.0.0"
tags = ["Render", "User Interface"]
license = ["SPDX:GPL-3.0-or-later"]
