name = "Light Helper"
id = "LightHepler"
maintainer = "ACGGit"
version = "2.0.0"
tagline = "Manage light linking and exclusions from the sidebar"
blender_version_min = "4.2.0"
type = "add-on"
schema_version = "1.0.0"
tags = ["Lighting"]
license = ["SPDX:GPL-3.0-or-later"]
support = "https://github.com/AIGODLIKE/LightHelper/issues/9"
website = "https://github.com/AIGODLIKE/LightHelper"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/.github/",
    "/.idea/",
    "/dist/",
    "/*.zip",
    "/.gitignore",
    "/README.md",
    "*.md",
    "**/*.pyc",
    "**/*.pyo",
    "**/*.log",
]
