name = "Light Helper"
id = "LightHepler"
maintainer = "Atticus, AIGODLIKE Community"
version = "0.3.0"
tagline = "Light Helper"
blender_version_min = "4.2.0"
type = "add-on"
schema_version = "1.0.0"
tags = ["Render","User Interface"]
license = ["SPDX:GPL-3.0-or-later"]
